# Generated by Django 4.1.7 on 2023-03-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
